dist: trusty
sudo: required
language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - docker pull truffle/ci
  - docker pull ethereum/client-go:latest

env:
  - TEST=repo GETH=true
  - TEST=repo
  - TEST=upstream
  - TEST=scenario

matrix:
  allow_failures:
    - env: GETH=true

script:
  - npm run test:ci
